version: "3.8"

services:
  # Laravel API Service using Octane (Swoole)
  perpustakaan_prod_api:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    container_name: perpustakaan_prod_api
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
    expose:
      - "8000"
    networks:
      - perpustakaan_prod_network

  # Nginx service for reverse proxy
  perpustakaan_prod_nginx:
    image: nginx:stable-alpine
    container_name: perpustakaan_prod_nginx
    restart: always
    ports:
      - "80:80" # Expose port 80 for HTTP access
    volumes:
      - .:/var/www
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - perpustakaan_prod_api
    networks:
      - perpustakaan_prod_network

networks:
  perpustakaan_prod_network:
    name: perpustakaan_prod_network
    external: true
