# ./docker-compose.dev.yml
services:
  perpustakaan_dev_api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: perpustakaan_dev_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - perpustakaan_dev_rabbitmq
    env_file:
      - .env
    expose:
      - "9000"
    networks:
      - perpustakaan_dev_network

  perpustakaan_dev_nginx:
    image: nginx:stable-alpine
    container_name: perpustakaan_dev_nginx
    restart: unless-stopped
    ports:
      - "80:80" # Access via http://localhost
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    depends_on:
      - perpustakaan_dev_api
    networks:
      - perpustakaan_dev_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    networks:
      - perpustakaan_dev_network

  perpustakaan_dev_rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: perpustakaan_dev_rabbitmq
    restart: always
    ports:
      - "5677:5672"
      - "15677:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=hessrL2Pc9PFs0TV5YrfYovQ
    networks:
      - perpustakaan_dev_network

  # Supervisor
  perpustakaan_dev_rabbitmq_supervisor:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: perpustakaan_dev_rabbitmq_supervisor
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - perpustakaan_dev_rabbitmq
      - perpustakaan_dev_api
    env_file:
      - .env
    command: ["php", "artisan", "rabbitmq:supervisor"]
    networks:
      - perpustakaan_dev_network

networks:
  perpustakaan_dev_network:
    name: perpustakaan_dev_network
    external: true
