# ./docker-compose.dev.yml
services:
  perpustakaan_dev_api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: perpustakaan_dev_api
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --watch
    networks:
      - perpustakaan_dev_network
    depends_on:
      - perpustakaan_dev_db

  perpustakaan_dev_db:
    image: postgres:16.8-alpine3.20
    container_name: perpustakaan_dev_db
    restart: always
    environment:
      - POSTGRES_DB=db_perpustakaan
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=90N7/LCjJl6A
    ports:
      - "5462:5432"
    volumes:
      - perpustakaan_dev_db_data:/var/lib/postgresql/data
    networks:
      - perpustakaan_dev_network

  perpustakaan_dev_nginx:
    image: nginx:stable-alpine
    container_name: perpustakaan_dev_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - perpustakaan_dev_api
    networks:
      - perpustakaan_dev_network

volumes:
  perpustakaan_dev_db_data:
    name: perpustakaan_dev_db_data
    driver: local

networks:
  perpustakaan_dev_network:
    name: perpustakaan_dev_network
    driver: bridge
