# ./docker-compose.dev.yml
services:
  perpustakaan_dev_api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: perpustakaan_dev_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - perpustakaan_dev_network

  perpustakaan_dev_nginx:
    image: nginx:stable-alpine
    container_name: perpustakaan_dev_nginx
    restart: unless-stopped
    ports:
      - "80:80" # Access via http://localhost
    volumes:
      - .:/var/www
      - ./docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - perpustakaan_dev_api
    networks:
      - perpustakaan_dev_network

networks:
  perpustakaan_dev_network:
    name: perpustakaan_dev_network
    external: true
