compose-dev-file=docker-compose.dev.yml
container-app-dev=perpustakaan_dev_api

local-clear:
	php artisan cache:clear && php artisan config:clear && php artisan route:clear

local-migration-run:
	php artisan migration

local-seed-run:
	php artisan db:seed

local-run:
	php artisan serve


# Deploy Dev
app-dev-deploy:
	docker compose -f $(compose-dev-file) up -d --force-recreate --remove-orphans

app-dev-deploy-watch:
	docker compose -f $(compose-dev-file) up --force-recreate --remove-orphans

app-dev-log:
	docker logs -f $(container-app-dev)

app-dev-migrate:
	docker-compose -f $(compose-dev-file) exec $(container-app-dev) php artisan migrate

app-dev-seed:
	docker-compose -f $(compose-dev-file) exec $(container-app-dev) php artisan db:seed

app-dev-composer:
	docker compose -f $(compose-dev-file) exec $(container-app-dev) composer install

app-dev-storage-link:
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan storage:link

app-dev-setup:
	docker compose -f $(compose-dev-file) exec $(container-app-dev) composer dump-autoload

app-dev-key-generate:
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan key:generate
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan jwt:secret

app-dev-clear:
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan config:clear
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan cache:clear
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan route:clear
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan optimize:clear
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan config:cache

app-dev-db-setup:
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan migrate
	docker compose -f $(compose-dev-file) exec $(container-app-dev) php artisan db:seed

app-dev-down:
	docker compose -f $(compose-dev-file) down

app-dev-sh:
	docker exec -it $(container-app-dev) sh

app-dev-net:
	docker exec -it  $(container-app-dev) netstat -tulpn | grep 8000
